#pragma once

// This is from glfw3.h
#define CL_MOUSE_BUTTON_1			0
#define CL_MOUSE_BUTTON_2			1
#define CL_MOUSE_BUTTON_3			2
#define CL_MOUSE_BUTTON_4			3
#define CL_MOUSE_BUTTON_5			4
#define CL_MOUSE_BUTTON_6			5
#define CL_MOUSE_BUTTON_7			6
#define CL_MOUSE_BUTTON_8			7
#define CL_MOUSE_BUTTON_LAST		CL_MOUSE_BUTTON_8
#define CL_MOUSE_BUTTON_LEFT		CL_MOUSE_BUTTON_1
#define CL_MOUSE_BUTTON_RIGHT		CL_MOUSE_BUTTON_2
#define CL_MOUSE_BUTTON_MIDDLE		CL_MOUSE_BUTTON_3
